### ISSUE TITLE
Style for News featured items strip

### ISSUE THREAD

**Issue by valeriapesce** [godanSec/Website#1]
It seems the style for the Featured items under News is not the same as the style in other featured sections in the website: under Research and Events, if there are three items they take the whole strip and the images are bigger; under News, if there are three items, they have the same size as if they were 6 and they're aligned on the left.

**Comment by valeriapesce** [comment]
News alignment:
![news-featured](https://cloud.githubusercontent.com/assets/6312089/13852937/cfc67bce-ec64-11e5-8adb-0192fc91fa47.PNG)

Success stories alignment:
![featured-success-stories](https://cloud.githubusercontent.com/assets/6312089/13852948/d7592c74-ec64-11e5-8404-9015fdc759fa.PNG)

**Comment by VTsantilis** [comment]
The news featured section actually has 6 items but the last one has no image-media, so the space is reserved but no media is displayed. It can be solved by adding an extra filter to the respective views

**Comment by valeriapesce** [comment]
_From AgroKnow:_

Fixed in dev.
