### ISSUE TITLE
crm@godan.info linked to new Drupal CRM

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#11]
If I use crm@godan.info to BCC emails, will it go to the new Drupal CRM in the interim?

**Comment by stoitsis** [comment]
@anabrandusescu we need the credentials for the SMTP server to be entered in the new CRM. We have sent an email to Martin.

**Comment by stoitsis** [comment]
@anabrandusescu this should be working fine now. If yes please close the issue.

**Comment by anabrandusescu** [comment]
Thanks!
