### ISSUE TITLE
'Organisation info' in CRM does not upload on website when saved under inline option

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#15]
This functionality will really speed up the process.

**Comment by stoitsis** [comment]
Ana, as mentioned in our call supporting inline editing for all the blocks in CRM will results to have many automatic rules run during save. This can be a problem in the long run and we are not recommending this. What we could try is to support the update during inline editing only for some specific blocks e.g. generic info and organisation info. Which are the important blocks that you are editing most frequently?

**Comment by anabrandusescu** [comment]
ok - agree with you on specific blocks for inline editing. I mostly need 'organisation info' and 'add address' for quick edits

**Comment by VTsantilis** [comment]
Hi, inline edit is available for organisation info. Please check if it's ok and close this. 
From the address only the country is used on drupal content. If you update country in an inline edit for an existing address it is updated for drupal content too. If you add one more address to organization from inline edit and set it as primary address the country on drupal side is updated to match the new primary address.
Thanks

**Comment by anabrandusescu** [comment]
Thanks Vasilis!
