### ISSUE TITLE
White spacing under main menu

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#16]
![menubanner](https://cloud.githubusercontent.com/assets/17909896/13916588/6c829d4e-ef53-11e5-884c-43660aaaaa2e.JPG)

Hi - there is odd white spacing underneath main menu on the left and right sides of the screen - just a minor design issue but the eye gets caught here. (see picture)

Thanks,
Diana

**Comment by valeriapesce** [comment]
Fixed in dev
