### ISSUE TITLE
Footer - odd spacing

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#17]
Hi,

There is slightly odd alignment / spacing in the footer -- not sure if its supposed to be left-aligned but is it possible to get it even spaced across the entire footer? See picture.

Thanks
Diana
![footer](https://cloud.githubusercontent.com/assets/17909896/13916636/c380b7f2-ef53-11e5-8819-e9b41eac4674.JPG)

**Comment by valeriapesce** [comment]
_From Agriknow:_

Fixed in dev
