### ISSUE TITLE
HTML of content

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#18]
![stories html](https://cloud.githubusercontent.com/assets/17909896/13916760/66ede72a-ef54-11e5-9fbc-d97b8fb889da.JPG)

Hi (see pic) it doesn't look like the HTML / spacing was carried over for a lot of the stories and they are just in big blocks of text - is it not possible to have the content spaced out as it was originally published in the old website?

Thanks
Diana

**Comment by valeriapesce** [comment]
_From AgroKnow:_

The HTML was imported as it was in the Wordpress export.
There are two issues:
1) Some contents contained Wordpress shortcodes, which cannot be processed by Drupal (except for a few);
2) The events manager was an additional Wordpress plugin which created some formatting on the fly, which cannot be exported.

For the moment we adjusted the formatting of most events manually.
