### ISSUE TITLE
Grey shading of featured box

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#21]
![grey](https://cloud.githubusercontent.com/assets/17909896/13918737/0119b0a2-ef61-11e5-9e0b-a2a1a107d7eb.JPG)

The grey shading of the feature box bleeds into the left but not on the right of the screen when you are viewing the website on a widescreen desktop (see pic)

**Comment by VTsantilis** [comment]
fixed can you verify?
