### ISSUE TITLE
Statement of Purpose page

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#27]
I've edited the content on this page to have paragraph breaks between almost every sentence, but when the changes are saved, the content at the top of the page still appears in large, chunky paragraphs

Also, from the '**About page**' there is a request to have 'Our vision' in the right-hand menu changed to 'Statement of Purpose' which then leads us to this page:

http://test-godan-new.pantheonsite.io/pages/about/statement-purpose

**Comment by valeriapesce** [comment]
Hi Diana,

AK made some changes to address this, could you try again now?
The content of the page in English was being updated but the version displayed was the "Language neutral" one, for some strange reason.
It seems that the correct version is displayed now, so any change you make should be reflected immediately.

In case you don't see the bullet points, they fixed that in dev and will push the change to test soon.

The menu item has been changed.

**Comment by dianaszpotowicz** [comment]
Great, thank you. 

Can I just ask that ‘Purpose’ in Statement of Purpose, in the page headline and the menu item be capitalized, since it is a formal noun?

I’m continuing to add events on the page and a lot of them are coming out with bugs with bullet points appearing to the left. I put examples of this in Github.

Thanks for all your help!

Kind regards,

Diana Szpotowicz

Strategic Communications Advisor 

Global Open Data for Agriculture and Nutrition (GODAN)

Diana.Szpotowicz@godan.info

+44 01491 829315

@godanSec

**Comment by valeriapesce** [comment]
Menu item capitalized.
