### ISSUE TITLE
Partners page - links showing up

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#28]
Hi,

Not sure if this is a bug but I just clicked on the Partners page (not logged in) and this small link / text showed up on the top right corner of the page... I'm not sure what it is for? (See image)

![leaflet](https://cloud.githubusercontent.com/assets/17909896/14105365/176b4f44-f5a3-11e5-9c5f-4d23bb9b63de.JPG)

**Comment by VTsantilis** [comment]
fixed

**Comment by stoitsis** [comment]
@dianaszpotowicz please close this issue. Thank you.
