### ISSUE TITLE
Mandatory title on pages

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#32]
![abouttitle](https://cloud.githubusercontent.com/assets/17909896/14279735/dbd96c98-fb26-11e5-8b6e-1ed039616061.JPG)

Hi, I wanted to update the ABOUT page to not have a title, which was 'About GODAN' because we already have 'ABOUT' on the page so its redundant to have it in the title again. Is it possible to get rid of this mandatory 'title' (it currently has a red asterisks that makes it mandatory to fill this in before publishing)

**Comment by VTsantilis** [comment]
Title is mandatory and used to identify content. What can be done is to hide the title for the specific page.
It will look like this
![about_godan](https://cloud.githubusercontent.com/assets/8608412/14391053/86c4cf7e-fdc2-11e5-9ff2-0d33c06f0884.png)
if you agree i will hide it for the about page. If you want to have the ability to selectively hide titles we can implement a solution so when you enter a special character the title will not be displayed.

**Comment by stoitsis** [comment]
@dianaszpotowicz hiding the title is not the best solution from the SEO point of view. I would suggest just hiding the About teaser block only in the about page as indicated in the screen. Let me know if you agree and we can do that very soon. The block can be shown in the rest of the pages of the About section.

![hide the about](https://cloud.githubusercontent.com/assets/3452880/14638763/9576388c-0641-11e6-9cf5-f9bd2460a422.png)

**Comment by dianaszpotowicz** [comment]
Ok sure I agree to that. 

Kind regards,

Diana Szpotowicz

Strategic Communications Advisor 

Global Open Data for Agriculture and Nutrition (GODAN)

Diana.Szpotowicz@godan.info

+44 01491 829315

@godanSec

**Comment by stoitsis** [comment]
@dianaszpotowicz please check now. If it is ok please close the issue. thank you.
