### ISSUE TITLE
Sign-in tab on website

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#33]
The sign-in tab on website should not be displayed yet. We are not ready to give users individual accounts at the moment. Please note that we still need this feature internally for future launch.

**Comment by anabrandusescu** [comment]
![sign-in tab](https://cloud.githubusercontent.com/assets/3058770/14294398/cf525d6c-fb68-11e5-8ed7-0828b3bc89fe.png)

**Comment by stoitsis** [comment]
OK, we will do that. I will let you know as soon as we will fix it.

**Comment by stoitsis** [comment]
@anabrandusescu just keep in mind that if we remove the sign in link then you will need to remember the http://www.godan.info/user link to be able to login into the admin and crm. Is that OK?

**Comment by anabrandusescu** [comment]
@stoitsis that's ok. Could you please send out an email to everyone who has admin permissions to login via this link?

**Comment by stoitsis** [comment]
@anabrandusescu please close this issue. thank you.
