### ISSUE TITLE
partner sign-up form linked to GODAN Partners (Organizations) group in CRM

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#34]
Sign-up form for prospective partners on website should not automatically link to GODAN Partners (Organizations) group in CRM. 

When a new partner registers online, they should be linked to GODAN Prospective Partners (Organizations)

**Comment by stoitsis** [comment]
OK, we will fix that and will let you know.

**Comment by VTsantilis** [comment]
Changed.
Previously when a new organization was registered from the become partner form, Godan partners group was assigned to the crm entry and the respective drupal content with organization info was published (visible on partners page etc..) now the GODAN Prospective Partners group is automatically assigned to the new crm organizations and the drupal related content is unpublished (not visible on partners page).
When you change the group for the crm contact (from Prospective Partners --> Godan Partners ) the drupal node is published too.
If this is the desired behavior you can close this issue.

**Comment by anabrandusescu** [comment]
thanks!
