### ISSUE TITLE
partner sign-up form: add statement of purpose and consent fields

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#39]
![partner-signup-form](https://cloud.githubusercontent.com/assets/3058770/14383084/f975ea88-fd92-11e5-9896-ae0e0aafc693.png)

https://docs.google.com/forms/d/1uJBBb0osSKsCwakk4YZ6hkqNT2DbRdnBqZWViIc6c7U/viewform

**Comment by VTsantilis** [comment]
added please verify
