### ISSUE TITLE
godanSec slideshare account on website

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#40]
We should link the godanSec slideshare account to the website: 

http://www.slideshare.net/godansec

Perhaps as a social media button or as a part of a tab - maybe events since these presentations were given at past GODAN related events. @dianaszpotowicz @stoitsis - thoughts?

**Comment by VTsantilis** [comment]
added, check header social icons and footer

**Comment by anabrandusescu** [comment]
thanks!
