### ISSUE TITLE
Partner page: 'organisation info' in-line or via edit content in CRM does not update on website 

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#41]
e.g. Food Tank

**Comment by anabrandusescu** [comment]
Food Tank now appears on partner page. However I tried the next org down the list, FoodTrade, and it doesn't work.

**Comment by stoitsis** [comment]
@anabrandusescu Ana I just updated inline the food trade both in test and live and it worked. What is exactly the problem. Can you describe the steps?

**Comment by VTsantilis** [comment]
Cannot reproduce the issue. Inline and normal editing looks like working fine. Please check the organization after you change the crm info while you are logged in. If you are viewing partners page as guest you may get an outdated version because of caching mechanism to improve site performance.

**Comment by anabrandusescu** [comment]
Thanks @stoitsis @VTsantilis ! It works now. Probably was the caching mechanism.
