### ISSUE TITLE
partner page: partner map org point tabs

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#42]
could we include city, country, and website in the tab? 

![map-tab](https://cloud.githubusercontent.com/assets/3058770/14524336/22c72c72-0238-11e6-8f2a-77782e4bd252.png)

**Comment by VTsantilis** [comment]
added! please review and close issue

**Comment by anabrandusescu** [comment]
it works! could you please remove the website as the organisation title is clickable?

thanks in advance.

**Comment by VTsantilis** [comment]
Ok removed!
