### ISSUE TITLE
partner page: partner missing 

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#44]
Colombia Government is not displayed even though they are in CRM under GODAN Partner (Organizations)

**Comment by stoitsis** [comment]
@anabrandusescu I assume that you add the GODAN partner group using the Groups tabs and not by editing the CRM organisation contact. Just to remind you that the update of the info is fully supported only when using edit button. We just did it and it worked fine.

**Comment by anabrandusescu** [comment]
@stoitsis oops, my fault. thanks for the reminder!
