### ISSUE TITLE
error: new partner registration contact conflicts with existing CRM contact

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#45]
When a new organisation signs up and the contact point already exists in CRM, they are not able to register their organisation.

Can they be able to register even if they already exist in our CRM (most likely linked to prospective partner group)?

@VTsantilis @stoitsis

**Comment by VTsantilis** [comment]
@anabrandusescu When the become partner form is submitted, if the contact point information exists already in crm (based on email) the crm contact is updated. So we used this approach to prevent existing crm contacts to be updated (regarding first name - last name). We disabled this and added an information message so everyone now will be able to register even if they already exist in CRM.
If you agree you can close this.

**Comment by anabrandusescu** [comment]
excellent! so just to double check. the individuals will no be duplicate contacts?

**Comment by VTsantilis** [comment]
@anabrandusescu no the individuals created from this form are matched based on email and the individual found is updated no duplicate individual is created but only first name - last name are updated based on the latest input. You can check anytime for duplicate contacts and merge them from crm admin interface.

**Comment by anabrandusescu** [comment]
@VTsantilis perfect. thanks again
