### ISSUE TITLE
Adding a "Joined as partner" timestamp field to CIVI

### ISSUE THREAD

**Issue by benschp** [godanSec/Website#46]
To be able to track who did join GODAN over the past month or so (and eventually show on the website) we need to add a time stamp to Civi.

**Comment by stoitsis** [comment]
@benschp just to cross check that we are getting this right: you need the date that you are changing the group of a CRM contact from prospective to GODAN parter or the submission date of the registration form? Just to remind you that there is a created date field in Civi. You could use this field for your reports.

**Comment by benschp** [comment]
That would be perfect indeed if we can use the dat in the submission of the registration form, then it is already automated. If this route is no problem then this issue is solved I think.

Thanks a lot!

Ben

On 19 apr. 2016, at 13:23, Giannis Stoitsis notifications@github.com wrote:

@benschp https://github.com/benschp just to cross check that we are getting this right: you need the date that you are changing the group of a CRM contact from prospective to GODAN parter or the submission date of the registration form? Just to remind you that there is a created date field in Civi. You could use this field for your reports.

**Comment by stoitsis** [comment]
Yes using the created date in civi is the right way to do that as this is the same with the date that the partner submitted the form.

**Comment by anabrandusescu** [comment]
@stoitsis @benschp what if the partner already exists in the Prospective Partners group? Some partners already exist in that group - partners who we have been in contact with but have not yet signed up.

**Comment by benschp** [comment]
Isn’t Giannis referring to the partner registration form? That is a one time only form right?

On 19 apr. 2016, at 14:45, Ana Brandusescu notifications@github.com wrote:

@stoitsis https://github.com/stoitsis @benschp https://github.com/benschp what if the partner already exists in the Prospective Partners group?

**Comment by anabrandusescu** [comment]
@benschp yes and no. Once they sign up they also create an organisation that is linked to Civi and the partners automatically go into the Prospective Partners group

**Comment by stoitsis** [comment]
Yes I am referring to the partners that are registered through the form. Here is the question again: do you want the time that the partner becomes prospective or becomes GODAN partner? These are two different times. The first one is the same with date created in Civi. For the second we have this info in Drupal. It is the date that the Organisation node is published.

**Comment by anabrandusescu** [comment]
the time that the partner becomes GODAN partner. @benschp do you agree?

**Comment by benschp** [comment]
Yes, we want the date that the partner registration form is submitted (from Drupal).

Ben

On 19 apr. 2016, at 14:52, Giannis Stoitsis notifications@github.com wrote:

Yes I am referring to the partners that are registered through the form. Here is the question again: do you want the time that the partner becomes prospective or becomes GODAN partner? These are two different times. The first one is the same with date created in Civi. For the second we have this info in Drupal. It is the date that the Organisation node is published.

**Comment by benschp** [comment]
Sorry, double post, 

yes, the partner registration form time from drupal. 

On 19 apr. 2016, at 15:01, Ana Brandusescu notifications@github.com wrote:

the time that the partner becomes GODAN partner. @benschp https://github.com/benschp do you agree?

**Comment by stoitsis** [comment]
@anabrandusescu @benschp the date when the Organisation became Godan partner is displayed in the Groups tab of the CRM contact. Check the screen. So you have the info that you need. Let us know if anything else is needed about that.
![screen](https://cloud.githubusercontent.com/assets/3452880/14714521/f49e759c-07ed-11e6-8bbe-60b19b8ab9ca.png)

**Comment by benschp** [comment]
Thanks, that is the date when they have been added to the group.

However, we want to have the date of the submission of the webform on the
new drupal site. For historic submissions this does not work so we will
need to make an estimate.

**Comment by stoitsis** [comment]
@benschp after 31/3 the date of the webform is exactly the same with the date created field in civic.
