### ISSUE TITLE
partner sign-up form: revised list of 'Organisation type'

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#48]
Could you please change the existing Organisation Type list to:

-Foundation  
-Government
-Government Agency  
-International Organisation  
-NGO  
-Private Sector  
-University / Research Institution
-Other (please specify)

**Comment by stoitsis** [comment]
@anabrandusescu to do that we need a table that will map the current types to the new ones proposed here e.g. old: Foundation organisation new: Foundation. Its better to rename the tags and not to delete them. Also its not possible to have "Please specify". We can only have Other as a tag value.

**Comment by anabrandusescu** [comment]
@stoitsis thanks

table with old/new organisation types is available here: https://docs.google.com/document/d/1X5LLdhEf_J9H93tggKdz7uGxyD6-H_YH1aEjGy1quEg/edit#heading=h.nfuxx1q2rrwi

and noted. 'Other' tag is fine

**Comment by VTsantilis** [comment]
@anabrandusescu thanks for the list. We will update the organization types as suggested within an hour.
After the update the removed tags will no longer be available for the crm contacts or the drupal organizations even if they have been tagged in the past, i suppose you are fine with this

**Comment by anabrandusescu** [comment]
@VTsantilis thanks for the update. Yes, we are fine with this

**Comment by VTsantilis** [comment]
@anabrandusescu Completed. Please check and close the issue.

**Comment by anabrandusescu** [comment]
@VTsantilis thanks! when can we start tagging the partners in the CRM?

**Comment by VTsantilis** [comment]
@anabrandusescu You can work with the tagging, there is no issue we have removed the suggested organization types and renamed some. The renamed organization types are available in CRM

**Comment by anabrandusescu** [comment]
@VTsantilis ok just double checking because @stoitsis advised not to retag anything in CRM until you are done work on the advanced partners page/functionality

**Comment by anabrandusescu** [comment]
update: @VTsantilis I've spoken to @stoitsis and we can start tagging the organisations in the CRM cc/ @benschp
