### ISSUE TITLE
Spelling error in page description

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#49]
Hi,

I can't find where to edit the page description of the Summit 2016 page - when I click 'edit' the page, it shows the description as blank... there is a typo that needs to be fixed (see attached)
![summitspellingerror](https://cloud.githubusercontent.com/assets/17909896/14739768/bbdfb86c-0881-11e6-8430-98bb68779eb9.JPG)

**Comment by VTsantilis** [comment]
@dianaszpotowicz fixed.
Here is a screen how to edit similar blocks of content. While logged in, just hover above the text and click the gear icon shown closest to the text.
![summit-block-edit](https://cloud.githubusercontent.com/assets/8608412/14782900/d2aa8430-0af4-11e6-948b-20be416b2239.png)

**Comment by stoitsis** [comment]
@dianaszpotowicz if everything is fine with that please close the issue.
