### ISSUE TITLE
partner page: mobile response to viewing partners by country

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#50]
When trying to look at the partners from a particular country on a phone, if you try and select a country to view its partners, the page reloads before you have a chance to actually select a partner.

**Comment by stoitsis** [comment]
@anabrandusescu did you mean before selecting another country? Because after selecting a country the page reloads and shows you only the partners for this country.

**Comment by anabrandusescu** [comment]
@stoitsis this comment originally came from a user. I just checked myself and yes, I think they had meant before. when I try to change the country the page automatically reloads.

**Comment by stoitsis** [comment]
@anabrandusescu the idea is that you can add incrementally after each page load the new country. We can try to disable the automatic load. We will try it and let you know.

**Comment by stoitsis** [comment]
@anabrandusescu we have disable the automatic load and we added a button to apply the filter in the dev http://dev-godan-new.pantheonsite.io/partners. Please check it and let us know.

**Comment by anabrandusescu** [comment]
@stoitsis thanks! it works

**Comment by VTsantilis** [comment]
@anabrandusescu we have added the search button on live site too, you can close this issue
