### ISSUE TITLE
Attachments not showing up under document pages

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#52]
Hi.

When you are logged in, and attached a downloadable document /link to a page - it shows up right away. But when you log out of your account, the link to the document disappears! Not sure why? This can be viewed on the ODI paper page 

http://www.godan.info/documents/how-can-we-improve-agriculture-food-and-nutrition-open-data

**Comment by VTsantilis** [comment]
@dianaszpotowicz fixed. Please review and close this.
