### ISSUE TITLE
Auto-update number of GODAN partners

### ISSUE THREAD

**Issue by mlgonzalezusda** [godanSec/Website#54]
http://www.godan.info/pages/about-godan: 

Is there a way for the number of GODAN partners on this website needs to be hyperlinked to auto update. It is a static number currently (at 240)

Same is valid for following pages: 
http://www.godan.info/pages/thinking-becoming-godan-partner
http://www.godan.info/what-is-godan
http://www.godan.info/partners

**Comment by mlgonzalezusda** [comment]
Same is valid for page: http://www.godan.info/pages/thinking-becoming-godan-partner, where number is currently at 200.

**Comment by VTsantilis** [comment]
@mlgonzalezusda fixed. Please close.
