### ISSUE TITLE
Summit page description

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#56]
Hi,

I think for the Summit page we won't need this extra paragraph describing the Summit page... can we remove this from the page? See picture.

Thanks
Diana
![summitdescription](https://cloud.githubusercontent.com/assets/17909896/15041478/9ba967e2-12bc-11e6-81da-018b87baed2f.JPG)

**Comment by stoitsis** [comment]
@dianaszpotowicz yes you are right. I removed that. Please check and close the issue. Remember to clean your browser's cache if it is still displayed.
