### ISSUE TITLE
Printable list of partners

### ISSUE THREAD

**Issue by mlgonzalezusda** [godanSec/Website#57]
-          Enable a full print out, instead of having to click all the individual boxes
-          Print out list to include country and type of organization
-          Need to update the categories*\* and partner categorization as per file updated and discussed with Ana and Ben.

@anabrandusescu: do the developers have access to the partner file?

**Current categories are (only change is regarding Foundation): 
Non-profit / Foundation
Government
Government Agency
International Organisation
NGO
Private Sector
University / Research Institution
Other

**Comment by anabrandusescu** [comment]
@mlgonzalezusda - @benschp and I will be tagging the partner categories today in the CRM. As @benschp has already mentioned this morning in his email, we will keep the Foundation category as is. Non-profit for us is a parent category and includes both Foundation and NGO categories.

**Comment by anabrandusescu** [comment]
@mlgonzalezusda an update: we will try to get the developers to automatically input the partner file details in our CRM do save us time 

@stoitsis - can we do an automatic batch of the partner types similarly to what we did for the partner logos? please note I have shared with you the Google Spreadsheet

**Comment by VTsantilis** [comment]
@anabrandusescu partner types are updated according to the Spreadsheet

**Comment by anabrandusescu** [comment]
@VTsantilis thank you. Now the types should be available in the Advanced Partners page for sorting or downloading?

**Comment by VTsantilis** [comment]
@anabrandusescu Yes they are, type of organisation is added now to the pdf export too.
If you have no other updates you can close this issue.

**Comment by anabrandusescu** [comment]
@VTsantilis thanks for the progress on this. 

We have noticed though that there is double categorization, e.g. an organization labeled as a both Government and Government Agency, others labeled as International Organization and Other, or Foundation and Other. Could we have the type of organisation that is only listed in the spreadsheet? (one type per partner organisation) /cc @mlgonzalezusda

**Comment by anabrandusescu** [comment]
@VTsantilis second point: can you enable a full print out list without having to click on every box?

**Comment by stoitsis** [comment]
@anabrandusescu you do not need to select a filtering options to be able to export a print out list. When the page loads and lists all the partners you can just select export and you will get the full list.

**Comment by anabrandusescu** [comment]
@stoitsis noted. cc/ @mlgonzalezusda 

Could we have the printable list in alphabetical order?

**Comment by VTsantilis** [comment]
@anabrandusescu 
- list order : fixed
- double categorization : fixed
  Please check

**Comment by anabrandusescu** [comment]
@stoitsis @VTsantilis thanks! looks good
