### ISSUE TITLE
Sign up form missing partner categories

### ISSUE THREAD

**Issue by mlgonzalezusda** [godanSec/Website#59]
List of categories for organizations should mirror our partner categories. Please add the 2 following categories to the Sign up for on page http://www.godan.info/stay-up-to-date-with-the-godan-summit-2016/

University / Research Institution
Other

Currently the only categories listed are: 
 National Government
 National Government Agency
 Non-Governmental Organization
 International Organization
 Private Sector
 Foundation

**Comment by stoitsis** [comment]
@mlgonzalezusda this forms is not controlled by us. I think that @dianaszpotowicz  and/or @anabrandusescu has access to this form.

**Comment by anabrandusescu** [comment]
@stoitsis @VTsantilis could we please have full permission to edit the form? cc/ @mlgonzalezusda @dianaszpotowicz

**Comment by VTsantilis** [comment]
@anabrandusescu you will have to configure the respective google form. I do not have access to this one. You can find the form here https://docs.google.com/forms/d/1KhsaiXx5MyYYyWsvKoPkJl3tSYbOOiz1Qp_-09dNGkM

**Comment by anabrandusescu** [comment]
Thanks @VTsantilis - I've requested access to the form internally

**Comment by dianaszpotowicz** [comment]
has this been resolved?

**Comment by mlgonzalezusda** [comment]
Outdated, since form was intended to gather info from people wanting updates about the Summit.
