### ISSUE TITLE
Breadcrumb?

### ISSUE THREAD

**Issue by valeriapesce** [godanSec/Website#6]
I would remove the breadcrumb completely.
First of all, it's not used consistently: it’s enabled only for two main pages (About us and Summit) and for individual nodes.
Secondly, it’s redundant (repeating information on the current page) and not really useful to navigate: the website doesn’t have a deep hierarchical organization, so the breadcrumb is not needed. 

![breadcrumb](https://cloud.githubusercontent.com/assets/6312089/13853580/9a55c80c-ec67-11e5-827d-f5075f2c55cc.PNG)

**Comment by stoitsis** [comment]
We agree. We can remove it

**Comment by valeriapesce** [comment]
_From AgroKnow:_

Fixed in dev.
