### ISSUE TITLE
Photo in blog entry

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#60]
Hi,

I think it would look better if the cover photo of a blog entry just appears as the cover photo and not in the body of the blog as well. If this is could be resolved that would be great, thank you!
![blogphoto](https://cloud.githubusercontent.com/assets/17909896/15293286/3370693e-1b7f-11e6-995d-64e437c94c82.JPG)

**Comment by VTsantilis** [comment]
@dianaszpotowicz if you mean by "cover photo" the photo displayed on homepage featured area, we could hide - remove it from the blog body but we don't recommend this. There are cases where the blog body has no other images. Anyway, if you think it should be removed, it we can do this.

**Comment by dianaszpotowicz** [comment]
Hi  - no I meant the photo in the blog post itself. It just looks like its in a funny format, so best removed. We definitely still want the photo to show up on the home/news pages, etc. 

Basically if we can follow the structure of the news pages, that would be great. 

Kind regards,

Diana Szpotowicz

Strategic Communications Advisor 

Global Open Data for Agriculture and Nutrition (GODAN)

Diana.Szpotowicz@godan.info

+44 01491 829315

@godanSec

**Comment by VTsantilis** [comment]
@dianaszpotowicz Ok i have changed the blog posts layout to match the news layout.. you can check and unless you spot any issues you can close this.
