### ISSUE TITLE
Disappearing blog entry

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#61]
Hi,

With this latest blog entry 
![blogdisappearing](https://cloud.githubusercontent.com/assets/17909896/15312886/491df0a0-1bff-11e6-8eec-27de85228087.JPG) if I select 'featured on the homepage' the blog entry disappears off the homepage all together. 

I'd like it both featured on the homepage in the prominent "top 3 stories" spot, as well as on the newspage. 

Thanks
Diana

**Comment by stoitsis** [comment]
@dianaszpotowicz the resources that are selected as Featured at the home page will not be displayed on the home page grid. This was agreed long time ago to avoid duplicates on the same page. We tried to enable the Featured at home page and it worked fine.

**Comment by dianaszpotowicz** [comment]
I am a bit confused... we do want blog posts featured prominently... they are some of our most important posts. This piece is still not featured at the moment.

**Comment by stoitsis** [comment]
@dianaszpotowicz we have added this blog entry at the top 3 stories by selecting the featured option. Please check

**Comment by dianaszpotowicz** [comment]
Thank you its up there now.
