### ISSUE TITLE
Size of featured images for latest/top stories

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#64]
![spaceofimages](https://cloud.githubusercontent.com/assets/17909896/15470736/168d402e-20ea-11e6-8229-94f2ea6e2de8.JPG)

Hi,
What can we do to make the image of the story fit the size of the box for the images? For example, we really can't have the Summit logo be cut off awkwardly in the news story about the Summit (see image)... I can't see anywhere to adjust the photo size to certain dimensions for it to fit the square perfectly - can you tell me how to fix this?

Thanks
Diana

**Comment by VTsantilis** [comment]
@dianaszpotowicz hi Diana, featured images are scaled and cropped to match 500px x 500px dimensions. In order to display properly you should use a square image or at least a taller one do you have another image except this one http://www.godan.info/sites/default/files/news-media/GODANNewYork.jpg ??

**Comment by dianaszpotowicz** [comment]
![500pxphotos](https://cloud.githubusercontent.com/assets/17909896/15607423/f460dae8-2412-11e6-8d7e-8ea78039658a.JPG)
Hi - I had our graphic designer create the 500 px x 500 px image as requested (this is especially important for the Summit story) and the logo is still covered... is it possible to move down the description overlap a bit further down from the photo (so its more vertical) so it does not cover the summit logo, as seen in the image?

**Comment by VTsantilis** [comment]
@dianaszpotowicz Ok fixed! You can close this.
