### ISSUE TITLE
Font used in new stories

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#65]
Hi,

I just wanted to ask about the font that appears in news stories and blog posts, etc. on the GODAN website. We are supposed to have only headlines in Century Gothic, and the main written text should be in Arial... which I don't think it is now. How can we change this?

Thanks
Diana

**Comment by VTsantilis** [comment]
@dianaszpotowicz Yes you are right, fonts were set from modular based on mock ups. I have changed the main text fonts to arial on dev site (http://dev-godan-new.pantheonsite.io/) you can check it and if you agree i can make this change on live site too. I think we should apply this font family to all content and not only for news and blog posts.

**Comment by dianaszpotowicz** [comment]
Yes that looks good to me, thank you!

Kind regards,

Diana Szpotowicz

Strategic Communications Advisor 

Global Open Data for Agriculture and Nutrition (GODAN)

Diana.Szpotowicz@godan.info

+44 01491 829315

@godanSec

**Comment by VTsantilis** [comment]
@dianaszpotowicz OK.. Style applied on live site. If you spot any issues let me know, if not close this issue

**Comment by dianaszpotowicz** [comment]
Thank you - I have noticed a few issues. A few blog posts show half/half font of Arial and Century Gothic in the body of the text, please see this photo for an example: ![half](https://cloud.githubusercontent.com/assets/17909896/15824296/6e03cdd4-2bf6-11e6-87b7-a89a9920bc59.JPG)
In others, you can see the main body of the text as Arial, but "similar events" still display the text with Century Gothic font
![homepage](https://cloud.githubusercontent.com/assets/17909896/15824295/6dece1a0-2bf6-11e6-9a7d-d4fd54ff75e6.JPG)
Also, CG font still shows up on the homepage as the main body of text font (see attached)

**Comment by VTsantilis** [comment]
@dianaszpotowicz the above pages are fixed. Add links - screens if you find others with mixed fonts
