### ISSUE TITLE
Become a partner page - hyperlink to Statement of Purpose page

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#66]
![godan-issue1](https://cloud.githubusercontent.com/assets/3058770/15778431/7ec7e0fe-2996-11e6-8e01-a11b19b75f8a.png)

**Comment by VTsantilis** [comment]
@anabrandusescu Fixed please check and close this..

**Comment by anabrandusescu** [comment]
@VTsantilis thanks!
