### ISSUE TITLE
Summit page description

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#70]
Hi,

I thought we had gotten rid of this extra description on the Summit page? Somehow I see it's come back, and it has a spelling mistake. Can we please remove this as soon as possible?

Thank you
Diana 
![summitdescription](https://cloud.githubusercontent.com/assets/17909896/16006961/a9ad442a-3167-11e6-91a0-1ca1bd6c4a12.JPG)

**Comment by VTsantilis** [comment]
@dianaszpotowicz I think you are looking on the dev site. I cannot see it here : http://www.godan.info/pages/godan-summit-2016
