### ISSUE TITLE
partners page - location details in individual partner pages 

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#9]
The location displayed should only be city and country, with no comma before 'city'.
![partner-page-location-issue](https://cloud.githubusercontent.com/assets/3058770/13877179/866206ce-ed09-11e5-88b4-9618969cafbb.png)

**Comment by stoitsis** [comment]
Done. @anabrandusescu please check.

**Comment by anabrandusescu** [comment]
Thanks!
